### ISSUE TITLE
Problem with MathJax style

### ISSUE THREAD

**Issue by pjastr** [gap-system/GitHubPagesForGAP#14]
HTTPS enforcement is required for GitHub Pages sites using a github.io domain that were created after June 15, 2016. https://help.github.com/articles/securing-your-github-pages-site-with-https/

So there is problem with link to MathJax because it is via http. You have to manually correct it. Could this be improved directly in the package?

**Comment by fingolfin** [comment]
The MathJax link is already https in the current version.
