### ISSUE TITLE
Adding links to PackageInfo.g and PDF manual

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GitHubPagesForGAP#3]
Most of GAP packages list the URL of their PackageInfo.g file on their websites. It's not necessary for the user, but useful for the release manager, saving time from downloading the archive to get to the PackageInfo.g file. Also, this reminds to the package author that that file should be updated for every release likewise others (README and manuals)

Could we adjust the template such that it will contain a link to PackageInfo.g, and perhaps also to PDF version of the manual? Both are missing in http://gap-system.github.io/io/.

**Comment by fingolfin** [comment]
The PDF is may not even be on the website (indeed, the `release` script does not copy it to websites, as PDFs do not fit well into git repositories).

As to adding a `PackageInfo.g` link: I am not sure I understand what you want this for? You say it would make it more convenient for the release manager — but how exactly? As I understand, there are two possible situations: Nothing changed, then the old URL for the `PackageInfo.g` is still valid — and then scripts should take care of downloading that file and parsing etc., not the release manager. Or else the package moved. But then it should be the responsibility of the package maintainer(s) to send the URL of the `PackageInfo.g` to the release manager. If they don't do it, the release manager should not bother to search for it, IMHO.

What am I missing?

**Comment by olexandr-konovalov** [comment]
More than 2 years later, this issue matured and is fine to close, it seems :)

PDFs seem not to be worth efforts. The HTML version is most suitable for browsing on Web, and if anyone is interested in PDF, download the archive or find it on the GAP pages for packages. Keeping PDF under version control is a strong argument against it.

With `PackageInfo.g`, I agree that if `GitHubPagesForGAP` always places it in a a standard location with the URL of the form `http://gap-system.github.io/packagename/PackageInfo.g`, then indeed it's not needed.
