### ISSUE TITLE
Links to GAP ref manual don't work

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-system/GitHubPagesForGAP#5]
I just noticed that none of the links to main `ref` manual work in the html manual of a project (take Orb for example) whose pages are produced using `GitHubPagesForGAP`. Is there some way to resolve this?

**Comment by fingolfin** [comment]
I am not aware of an existing solution, i.e. I think packages _not_ using `GitHubPagesForGAP` have the same problem (but I did not check this extensively).

Anyway, two solutions come to mind: 
1. include a full copy of the GAP manual on the page, at the right relative location;
2. use a script to replace the relative URLs in your manual with working links, e.g. pointing to the GAP homepage. (This, however, only works as long as your local GAP manual matches the one on the GAP homepage; so if e.g. a new chapter gets inserted, links may break).

Option 2 could be implemented as part of the update script, I guess...

**Comment by fingolfin** [comment]
I resolved this with an update to the `release` script (from https://github.com/fingolfin/ReleaseTools) - it runs sed on the HTML files in `gh-pages`, replacing links involving `../../../doc` by corresponding links to gap-system.org.

**Comment by james-d-mitchell** [comment]
@fingolfin awesome! Thanks!
