### ISSUE TITLE
Explain how to combine autogenerated pages with own content

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/GitHubPagesForGAP#6]
Some packages may wish to put additional information about their package onto the package website. 

Of course, one could suggest to them that the overview page is simple and auto-generated (like overview pages on the GAP website, e.g. https://www.gap-system.org/Packages/example.html) and you can put any additional information that you want inside the manual. But that may not work and may discourage authors from using `GitHubPagesForGAP`. Examples of such details that they would like to publish on the website are: acknowledgements of funding, lists of papers citing the package, links to presentations related to the package etc. 

For such purposes, it would be good to explain how additional text may be added, and update GitHubPagesForGAP to ensure that this can be done in a convenient manner when the new release of the package is published or between releases.

**Comment by olexandr-konovalov** [comment]
I've done this in a couple of packages - nothing complicated at all, but maybe one sentence in the README file will be helpful.

**Comment by fingolfin** [comment]
Of course you are right. I'll try to do this at some point (though of course pull requests are also welcome ;-).

**Comment by fingolfin** [comment]
Actually, I added a README section on "Adjusting the content and layout" back in 2014 in commit 5826b336707334f2959a52e24a25f197023b06bf
