### ISSUE TITLE
Instructions for updating

### ISSUE THREAD

**Issue by cdwensley** [gap-system/GitHubPagesForGAP#8]
Some comments after successfully updating gh-pages for the utils package. 
Instruction 2:  should be "git remote" not "git remove". 
It's not just a question of whether gh-gap exists, but also whether it points to the correct place. 
I had to git remove my gh-gap and then git add the correct URL.  
Instruction 4:  my git complained that 'continue' was not an option in "git merge --continue", 
so I continued by repeatedly aborting and then doing a new "git pull gh-gap gh-pages". 
There were repeated conflicts in PackageInfo.g and README.md: git appeared to be combining chunks of these files from both utils and gh-pages.

**Comment by fingolfin** [comment]
Thanks, I updated the instructions again, hopefully addressing everything in your feedback.

**Comment by cdwensley** [comment]
Not sure that this is quite what you meant: 
     Make sure the gh-gap remote exists and is in doubt. If in doubt, just re-add it: 
Perhaps: 
     Make sure the gh-gap remote exists and has the correct URL. If in doubt, just re-add it:
